instance_name       = "OpenMPI-Node01"
instance_shape      = "VM.Standard.A1.Flex"
ssh_public_key_path = "server.key.pub"
subnet_cidr         = "10.0.0.0/24"
vcn_cidr            = "10.0.0.0/16"
#region              = "eu-frankfurt-1"
